# Pull base image
FROM node:21-alpine

WORKDIR /app

# This is required in low-memory environments (possibly need to setup swap)
ENV NODE_OPTIONS=--max_old_space_size=2048

# Install dependencies
COPY ./movimenti-fe/package.json .
COPY ./movimenti-fe/lingui.config.js .

RUN npm install

COPY ./movimenti-fe/public/ ./public
COPY ./movimenti-fe/src/ ./src

RUN npm run extract && npm run compile && npm run build

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3300"]
