version: "3.9"

services:
  web:
    build: .
    command: docker-entrypoint.sh
    volumes:
      - ./app/finanze:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "RAPIDAPI_KEY=${RAPIDAPI_KEY}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: