
x-web-template: &web-template
  build:
    dockerfile: ./Dockerfile_django
  env_file:
  - path: app/finanze/.env
    required: true

services:
  # web-dev: # deprecated
  #   <<: *web-template
  #   volumes:
  #     - .:/code # override base container code, for live updates
  #   profiles:
  #     - local_db
  #   environment:
  #     DJANGO_SETTINGS_MODULE: finanze.settings.dev
  #   ports:
  #     - 127.0.0.1:8001:8000
    
  # web: # deprecated
  #   <<: *web-template
  #   profiles:
  #     - production
  #   depends_on:
  #     - db
  #   ports:
  #     - 127.0.0.1:8000:8000

  # web-staging: # deprecated
  #   <<: *web-template
  #   profiles:
  #     - staging
  #   depends_on:
  #     - db
  #   ports:
  #     - 127.0.0.1:8002:8000

  react_backend:
    build:
      dockerfile: ./Dockerfile_django
    env_file:
    - path: app/finanze/.env
      required: true
    command: []
    depends_on:
      - db
    ports:
      - 127.0.0.1:8003:8000
    profiles:
    - development
    - production
    develop:
      watch: 
        # sync static content
        - path: ./app/finanze
          action: rebuild
          ignore:
          - templates
          - manage.py
          

  react_frontend:
    build:
      dockerfile: ./Dockerfile_react
      tags:
      - $REACT_FRONTEND_TAG
    profiles:
      - frontend
      - production
    ports:
      - 127.0.0.1:3300:3000
    env_file:
      - path: movimenti-fe/.env
        required: true
    
  db:
    image: postgres:13
    profiles:
    - development
    - production
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
