version: "3.9"

x-web-template: &web-template
  build: .
  command: ./docker-entrypoint.sh
  volumes:
    - .:/code
  ports:
    - 127.0.0.1:8000:8000
  environment:
    - "DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}"
    - "RAPIDAPI_KEY=${RAPIDAPI_KEY}"
    - "SECRET_KEY=${SECRET_KEY}" # to be put in .env file

services:
  web-dev:
    <<: *web-template
    profiles:
      - dev
    
  web:
    <<: *web-template
    profiles:
      - prod
    depends_on:
      - db
      
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    profiles:
      - prod

volumes:
  postgres_data:
