# Pull base image
FROM python:3.11

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y gettext

# Copy project
COPY docker-entrypoint.sh ./
COPY ./app/finanze/ ./app/finanze

WORKDIR /code/app/finanze/receipt_scanner
RUN pip install -r requirements.txt

WORKDIR /code

ENTRYPOINT [ "./docker-entrypoint.sh" ]