# Generated by Django 3.2.7 on 2022-01-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradinglog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_val', models.FloatField()),
                ('open_timestamp', models.DateTimeField()),
                ('high_val', models.FloatField()),
                ('high_timestamp', models.DateTimeField()),
                ('close_val', models.FloatField()),
                ('close_timestamp', models.DateTimeField()),
                ('volume_val', models.FloatField()),
                ('volume_timestamp', models.DateTimeField()),
                ('low_val', models.FloatField()),
                ('low_timestamp', models.DateTimeField()),
                ('regular_market_price', models.FloatField()),
                ('regular_market_time', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradinglog.stock')),
            ],
        ),
    ]
