# Generated by Django 3.2.7 on 2022-01-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradinglog', '0002_stockquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquote',
            name='regular_market_price',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='regular_market_time',
        ),
        migrations.AddField(
            model_name='stock',
            name='regular_market_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='regular_market_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
