# Generated by Django 3.2.7 on 2022-01-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradinglog', '0003_auto_20220123_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquote',
            name='high_timestamp',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='high_val',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='low_timestamp',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='low_val',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='open_timestamp',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='open_val',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='volume_timestamp',
        ),
        migrations.RemoveField(
            model_name='stockquote',
            name='volume_val',
        ),
    ]
