# Generated by Django 3.2.7 on 2022-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradinglog', '0004_auto_20220123_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='regular_market_time',
            field=models.DateTimeField(),
        ),
    ]
