# Generated by Django 3.2.7 on 2022-02-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradinglog', '0007_alter_stock_last_price_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_cost',
            field=models.FloatField(default=2.0),
        ),
    ]
