# Generated by Django 3.2.7 on 2022-03-13 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
