# Generated by Django 3.2.7 on 2022-03-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0002_assetbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalance',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
