# Generated by Django 3.2.7 on 2022-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0003_alter_assetbalance_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalance',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
