# Generated by Django 4.2.8 on 2024-03-14 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0008_assetbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimenti.subcategory'),
        ),
    ]
