# Generated by Django 5.0 on 2024-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0009_alter_movement_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='direction',
            field=models.FloatField(choices=[(1.0, 'Income'), (-1.0, 'Outcome'), (0.0, 'Null')]),
        ),
    ]
