# Generated by Django 5.0 on 2024-04-06 17:12

from django.db import migrations, models


def create_balance_category(apps, schema_editor):
    Category = apps.get_model("movimenti", "Category")
    balance_category = Category(category="BALANCE", direction=0.0)
    balance_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('movimenti', '0010_alter_category_direction'),
    ]

    operations = [
        migrations.RunPython(create_balance_category),
    ]
